### ISSUE TITLE
path.sort() -- '<' not supported between instances of 'CornerSegment' and 'CornerSegment'.

### ISSUE THREAD

**Issue by MvGulik** [tatarize/potrace#7]
Just doing some additional (dir)exploring of this version of potrace.
(_actually ... trying to figure out -the long way- how to detect the doughnut inner part so I can use it as clip-part_)

I got the error [ '<' not supported between instances of 'CornerSegment' and 'CornerSegment'] when using **path**.sort().

Considering the test image I used the error '_kinda_' makes sens. (_not a pro-coder myself._)
Not sure though if such a case its something the uses should take care of, or potentially potrace in some way. (?)

Used test image. (png <= svg)
![test_trace4](https://user-images.githubusercontent.com/666868/222394934-14fb6f6d-1087-4913-8b7b-b56ea5b14b20.png)
svg source (_never hurts_):
```
<svg
	xmlns="http://www.w3.org/2000/svg"
	viewBox="0 0 100 100"
	width="100"
	height="100"
	>
	<rect fill="#fff" x="-5" y="-5" width="110" height="110" />
	<rect fill="#000" x="15" y="15" width="70" height="70" />
	<rect fill="#fff" x="30" y="30" width="40" height="40" />
	<rect fill="#000" x="40" y="40" width="20" height="20" />
</svg>
```

**Comment by MvGulik** [comment]
[>Curves tree is currently non-implemented.](https://github.com/tatarize/potrace/blob/4a279373a86050554c32e1eb71a1e2aa2689f251/potrace/potrace.py#L69)
_Darn ... bummer._

**Comment by tatarize** [comment]
I tried the curve trees a bit, but I didn't have a good debugger to do the required debugging between the original C++ and the the Python. For the rest of it, I could use the javascript port as a proxy. But, they didn't implement the curve trees so I would have needed a more proper C debugger to make sure that stuff went correctly. It was mostly transcribed but with a couple bugs, And I would need to either have a co-debugging version that was corrected for that part or fully understand the original code.

But, that is absolutely the thing you'd need to know the insideness of the various paths. 

If you're able to use pypotrace I'd assume they'd have the right hooks to access it, depending on your usecases. This is largely because that code often wanted it's own compile and wouldn't work. 

But, it's apparently pretty cheap to tag the curve trees into the algorithm. Since you know everything is contained in the other sections, and there's no overlapping. So any path found without the flipped pixels of an original path is contained within that path and gets put into the tree. The hard part was that it used a linklist and needed a bunch more things to get that section to work as a purely transcription of the code.

The python there uses lists and to sort them you'd need Curve(p) to have comparisons defined. Sorting it would be kind of pointless since the path is specific to being in that specific order.

**Comment by tatarize** [comment]
The relevant section that would have created the list tree is a one-off. It's called after bm_to_pathlist (commented out here). And then just runs the one function which goes through the list in order and adds the item as a child if it passes the insideness check and adds the item as a sibling if it fails.

```C++
  while (heap) {
    /* unlink first sublist */
    cur = heap;
    heap = heap->childlist;
    cur->childlist = NULL;
  
    /* unlink first path */
    head = cur;
    cur = cur->next;
    head->next = NULL;

    /* render path */
    xor_path(bm, head);
    setbbox_path(&bbox, head);

    /* now do insideness test for each element of cur; append it to
       head->childlist if it's inside head, else append it to
       head->next. */
    hook_in=&head->childlist;
    hook_out=&head->next;
    list_forall_unlink(p, cur) {
      if (p->priv->pt[0].y <= bbox.y0) {
	list_insert_beforehook(p, hook_out);
	/* append the remainder of the list to hook_out */
	*hook_out = cur;
	break;
      }
      if (BM_GET(bm, p->priv->pt[0].x, p->priv->pt[0].y-1)) {
	list_insert_beforehook(p, hook_in);
      } else {
	list_insert_beforehook(p, hook_out);
      }
    }
```

I never managed to read this. But, I looking at it now I think it actually renders the path and then checks whether the first pixel in the path is black. Since due to the nature of these paths if filled in, the path then any subpath would necessarily have all their edges drawn black in there.

The insideness check is `if (BM_GET(bm, p->priv->pt[0].x, p->priv->pt[0].y-1))` which then sends to `head->childlist` if true, or `head->next` if false. 

It ran the code until the bitmap consisted of only white pixels. Then it used this same bitmap a little bit more. By rendering the xor_path() in the bitmap it drew the given shape, flipping the relevant bits. Then it checked the next path as to whether the first pixel of that path was colored black. If it was, then it got put as a child of this path. If it was not, it got placed as a sibling of this path. It then scheduled the remaining paths in the heap. 

A few things in there are still a bit vague but I do understand at least what it was trying to do. It got super-confusing for me and wasn't essential to the running of the program before. I don't know why it's only checking the next item. There's probably something about the required ordering that I'm not considering. 

I see how you check the insideness but not exactly how that leads to the tree being efficiently determined. Clearly each path can be determined from that rendering the bitmap each time. But, it seems like it's checking each based on the tree and only putting each ungrouped memeber as a child. I guess because the original order would require that parent-paths could never occur after child-paths, so if you checked all the places it could be it must be attach to the parent. Though I don't quite see why it wouldn't maybe attach to a grandparent. Unless permitting that would be acceptable.

**Comment by MvGulik** [comment]
**Sorting:**
So if I read it right that sorting option is just an internal used function, and not intended as a general user option.
(_Seems proper reason to close this issue (closing ? )_)

... The question "why sort" did briefly cross my mind, ... but I gave it no second thought.

**Insideness:**
Not pretending to understand all you wrote. Its still nice so see some additional writing about it.

**pypotrace:**
Roger that. I gave it a second try to get it installed and working (_Linux_), and this time I got it right.
(_Time to adjust my own code to get it updated. ... I got [this far](https://i.imgur.com/FTp2Gia.png), so I might as well go the extra mile_.)

Thanks for your time.

**Comment by MvGulik** [comment]
Ps: just some after thought.
Renaming that sort function to "_sort" could serve as a potential indicator (_to other users_) its not a general user option.

**Comment by tatarize** [comment]
The sort function is actually on the `list` which the program uses to try to remain more or less python-based. 

It's not something put on there in this port. In fact, if you could also send it a compare function that would decide the arrangement of CornerSegments it could actually be sorted. It's just that it's a list of path segments and doesn't make much sense to sort those. But, if you wanted to sort them, you'd just pass a function that could compare them to the sort function and sort it by that context.

Pypotrace is a fine port, it's just that it's sometimes is too harsh to get to consistently work on some other machines. I may understand the insideness routine there enough to actually perform it. If you're settled though that leaves the number of people needing me to revisit that at 0.

**Comment by MvGulik** [comment]
>The sort function is actually on the list ...

(_peeks inside the ide-debugger_) Aha. I see what you mean. (_bad mixed \_\_thinking\_\_ on my part._)

Without the need for that curve-tree feature. I would have not switched to Pypotrace (_for one because the reason you mention_).
So I would not sell your program short.

**Comment by MvGulik** [comment]
Last info/remark on child vs parent stuff.

It turns out that technically (_although not really advisable_) one could get the effect I was after without knowing which curves are child- and parent-curves.

Although using this approach, when using a fair number of relative large merged-paths, comes with a notable speed penalty (on hover flipping a least).

https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/fill-rule
```
<svg
	xmlns="http://www.w3.org/2000/svg"
	viewBox="0 0 100 100"
	width="100"
	height="100"
	>
<style type="text/css">
	path:hover {fill:#88f;}
</style>
<path
	fill-rule="evenodd"
	stroke="red"
	d="
		M 10,10  h80 v80 h-80 z
		M 30,30 h40 v40 h-40 z
	" />
</svg>
```
